Projeto Aplicado/Controllers/CadastroController.cs
using Projeto_Aplicado.Entidades;
using Projeto_Aplicado.Models;
using Microsoft.AspNetCore.Mvc;
using Projeto_Aplicado.Repositorios.Interfaces;
using System.Security.Cryptography;
using System.Text;
using System;

namespace Projeto_Aplicado.Controllers
{
    public class CadastroController : Controller
    {
        private readonly IAcessoRepository _acessoRepository;
        public CadastroController(IAcessoRepository acessoRepository)
        {
            _acessoRepository = acessoRepository;
        }
        public IActionResult Cadastro()
        {
            var model = new UsuarioModel();
            return View(model);
        }
        [HttpPost]
        public IActionResult Novo(UsuarioModel model)
        {
            if (ModelState.IsValid)
            {
                var usuario = new Usuario()
                {
                    Id = model.id,
                    Nome = model.Nome,
                    Sobrenome = model.Sobrenome,
                    Email = model.Email,
                    Senha = HashPassord(model.Senha),
                    DataNascimento = model.DataNascimento,
                    Regiao = new Regiao()
                    {
                        Id = model.id,
                        Bairro = model.Bairro,
                        Cidade = model.Cidade,
                        Estado = model.Estado
                    }
                };
                _acessoRepository.Cadastrar(usuario);
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }
        
        private string HashPassord(string password)
        {
            var sha = SHA256.Create();
            var byteArray = Encoding.Default.GetBytes(password);
            var hashedPassword = sha.ComputeHash(byteArray);
            return Convert.ToBase64String(hashedPassword);
            
        }

    }
}

Projeto Aplicado/Controllers/FormularioPowerBiController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Projeto_Aplicado.Entidades;
using Projeto_Aplicado.Models;
using Projeto_Aplicado.Repositorios.Interfaces;
using System;

namespace Projeto_Aplicado.Controllers
{
    public class FormularioPowerBiController : Controller
    {
        private readonly IPowerBiRepository _powerBiRepository;
        public FormularioPowerBiController(IPowerBiRepository powerBiRepository)
        {
            _powerBiRepository = powerBiRepository;
        }

        public IActionResult FormularioPowerBi()
        {
            Usuario sessionUser;
            try
            {
                sessionUser = JsonConvert.DeserializeObject<Usuario>(HttpContext?.Session.GetString("SessionUser"));

            }
            catch (Exception e)
            {
                return RedirectToAction("Login", "Login");
            }
            ViewBag.UsuarioSession = sessionUser.Id;
            var model = new PowerBiModel();
            return View(model);
        }
        public IActionResult Value(PowerBiModel model)
        {
            if (ModelState.IsValid)
            {
                var powerBi = new PowerBi()
                {
                    UsuarioId = model.UsuarioId,
                    value1 = model.value1,
                    value2 = model.value2,
                    value3 = model.value3,
                    value4 = model.value4,
                    value5 = model.value5,
                };
                _powerBiRepository.Salvar(powerBi);
                return RedirectToAction("PowerBi", "PowerBi");
            }
            return View(model);
        }
    }
}

Projeto Aplicado/Controllers/PowerBiController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Projeto_Aplicado.Entidades;
using Projeto_Aplicado.Models;
using System;

namespace Projeto_Aplicado.Controllers
{
    public class PowerBiController : Controller
    {
        public IActionResult PowerBi()
        {
            try
            {
                var sessionUser = JsonConvert.DeserializeObject<Usuario>(HttpContext?.Session.GetString("SessionUser"));
            }
            catch (Exception e)
            {
                ViewBag.Message2 = "Faça o login para poder acessar!!!";
                return RedirectToAction("Login", "Login");
            }
            var model = new PowerBiModel();
            return View(model);
        }
    }
}

Projeto Aplicado/Controllers/ProjetoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Projeto_Aplicado.Entidades;
using Projeto_Aplicado.Models;
using Projeto_Aplicado.Repositorios.Interfaces;
using System;
using System.Collections.Generic;
using System.IO;

namespace Projeto_Aplicado.Controllers
{
    public class ProjetoController : Controller
    {
        private readonly IProjetoRepository _projetoRepository;
        public ProjetoController(IProjetoRepository projetoRepository)
        {
            _projetoRepository = projetoRepository;
        }
        public IActionResult Index()
        {
            try
            {
                var sessionUser = JsonConvert.DeserializeObject<Usuario>(HttpContext?.Session.GetString("SessionUser"));
            }
            catch (Exception e)
            {
                return RedirectToAction("Login", "Login");
            }

            ViewBag.Projetos = _projetoRepository.BuscarTodosProjetos();
            return View();
        }

        public IActionResult Novo()
        {
            var model = new ProjetoModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult Novo(ProjetoModel model)
        {
            Usuario sessionUser;
            try
            {
                sessionUser = JsonConvert.DeserializeObject<Usuario>(HttpContext?.Session.GetString("SessionUser"));
            }
            catch (Exception e)
            {
                return RedirectToAction("Login", "Login");
            }

            if (ModelState.IsValid)
            {
                var projeto = new Projeto();
                projeto.Id = model.Id;
                projeto.Descricao = model.Descricao;
                projeto.Itens = model.Itens;
                projeto.Titulo = model.Titulo;
                projeto.Imagem = conversorImagem(model.Imagem);
                projeto.UsuarioId = sessionUser.Id;

                _projetoRepository.Salvar(projeto);
                return RedirectToAction("Index");
            }
            return View(model);
        }


        public string conversorImagem(List<IFormFile> img)
        {
            string retorno;
            foreach (var file in img)
            {
                using (var ms = new MemoryStream())
                {
                    file.CopyTo(ms);
                    var filebytes = ms.ToArray();
                    retorno = Convert.ToBase64String(filebytes);
                    retorno = "data:image/png;base64," + retorno;
                }
                return retorno;
            }
            return null;
        }

    }
}

Projeto Aplicado/Views/Shared/_Layout.cshtml
<style>
    #bordaCima {
        box-shadow: 0 3px 10px rgba(0, 200, 255, 0.5) !important;
    }

    .waves {
        position: relative;
        width: 100%;
        height: 10vh;
        margin-top: 2em;
        min-height: 50px;
        max-height: 150px;
    }

    .parallax > use {
        animation: move-forever 25s cubic-bezier(.55,.5,.45,.5) infinite;
    }

        .parallax > use:nth-child(1) {
            animation-delay: -2s;
            animation-duration: 7s;
        }

        .parallax > use:nth-child(2) {
            animation-delay: -3s;
            animation-duration: 10s;
        }

        .parallax > use:nth-child(3) {
            animation-delay: -4s;
            animation-duration: 13s;
        }

        .parallax > use:nth-child(4) {
            animation-delay: -5s;
            animation-duration: 20s;
        }

    @@keyframes move-forever {
        0% {
            transform: translate3d(-90px,0,0);
        }

        100% {
            transform: translate3d(85px,0,0);
        }
    }

    .cup {
        float: left;
        margin-left: -10%;
        position: absolute;
        width: 150px;
        height: 180px;
        border: 6px solid #262626;
        border-top: 2px solid transparent;
        border-radius: 15px;
        transform: scale(0.2);
        border-top-left-radius: 5px;
        border-top-right-radius: 5px;
        background: url(https://image.ibb.co/fmHm66/wave.png);
        background-position: 0px 350px;
        background-repeat: repeat-x;
        animation: filling 10s ease-in-out infinite;
        box-shadow: 0 0 0 6px #fff, 0 20px 35px rgba(0,0,0,1);
    }

        .cup:before {
            content: '';
            position: absolute;
            width: 50px;
            height: 80px;
            border: 6px solid #fff;
            right: -57px;
            top: 30px;
            border-top-right-radius: 35px;
            border-bottom-right-radius: 35px;
        }

    @@keyframes filling {
        50% {
            background-position: 3000px 0px;
        }

        100% {
            background-position: 6000px 350px;
        }
    }

    .dropdown-menu a:hover {
        background: rgba(22,27,34);
    }

    #titulo {
        font-weight: 600;
        font-size: 20px;
        background: -webkit-radial-gradient(rgba(0, 200, 255, 1), rgba(0, 200, 255, 0.3));
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
    }
</style>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projeto_Aplicado</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav style="background-color: #161B22" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark" id="bordaCima">
            <div class="container">
                <a asp-controller="Home" asp-action="Index"><div style="margin-top: -90px" class="cup"></div></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li style="margin-left: 50px" class="nav-item">
                            <a id="titulo" class="nav-link text-light" asp-controller="Home" asp-action="Index">Water Insights</a>
                        </li>
                        <li style="margin-left: 40px; margin-top: 4px" class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Cadastro" asp-action="Cadastro">Cadastro</a>
                        </li>
                        <li class="nav-item" style="margin-top: 4px">
                            <div class="dropdown">
                                <a style="cursor: pointer" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="dropMenu" class="nav-link text-light dropdown-toggle">Pesquisa</a>
                                <div style="background: #161B22" class="dropdown-menu" aria-labelledby="dropMenu">
                                    <a class="nav-link text-light dropdown-item" asp-area="" asp-controller="FormularioPowerBi" asp-action="FormularioPowerBi">Pesquisa sobre sua água!</a>
                                    <a class="nav-link text-light dropdown-item" asp-area="" asp-controller="PowerBi" asp-action="PowerBi">Mapa da água!</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item" style="margin-top: 4px">
                            <a class="nav-link text-light" asp-area="" asp-controller="Projeto" asp-action="Index">Projetos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style="position: absolute; bottom: 0px; right: 0; left: 0">
        <div>
            <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                 viewBox="0 24 150 28" preserveAspectRatio="none" shape-rendering="auto">
                <defs>
                    <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
                </defs>
                <g class="parallax">
                    <use xlink:href="#gentle-wave" x="48" y="0" fill="rgba(33, 113, 180, 0.7)" />
                    <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(33, 113, 180, 0.5)" />
                    <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(33, 113, 180, 0.3)" />
                    <use xlink:href="#gentle-wave" x="48" y="7" fill="rgba(33, 113, 180, 1)" />
                </g>
            </svg>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>